#!/usr/bin/env bash
# Does the following:
#   That create a file /var/run/myscript.pid containing the script PID.
#   The script displays "To infinity and beyond" indefinitely
#   The script displays "I hate the kill command" upon receiving a SIGTERM
#   The script displays "Y U no love me?!" upon receiving a SIGINT
#   The script deletes the file /var/run/myscript.pid and terminates upon
#+  The script receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
